"""Markdown report, suitable for pull request comments and archives."""

from __future__ import annotations

import re

from specguard.audit.evidence import build_view
from specguard.models.requirement import SEVERITY_ORDER
from specguard.models.result import AuditEntry, AuditReport, Status

_ICON = {
    Status.PASS: "PASS",
    Status.FAIL: "FAIL",
    Status.WARNING: "WARNING",
    Status.UNVERIFIED: "UNVERIFIED",
    Status.ERROR: "ERROR",
}


def _pct(value: float | None) -> str:
    return "n/a (nothing verified)" if value is None else f"{value:g}%"


def _inline(text: str) -> str:
    """Make text safe inside a Markdown table cell or line."""
    return re.sub(r"\s+", " ", text).replace("|", "\\|")


def _entry_block(entry: AuditEntry) -> list[str]:
    view = build_view(entry)
    req = entry.requirement
    lines = [
        f"### {view.heading} ({req.severity.value})",
        "",
        f"**Requirement:** {_inline(view.requirement)}",
        "",
    ]
    if entry.result.status in (Status.UNVERIFIED, Status.ERROR):
        lines += [f"**Reason:** {_inline(view.reason or entry.result.message)}", ""]
    else:
        if view.expected:
            lines.append(f"- **Expected:** {_inline(view.expected)}")
        if view.found:
            lines.append(f"- **Found:** {_inline(view.found)}")
        if view.reason and entry.result.status is Status.FAIL:
            lines.append(f"- **Result:** {_inline(view.reason)}")
    if view.where:
        more = f" (+{view.more_locations} more)" if view.more_locations else ""
        lines.append("- **Location:** " + "; ".join(view.where) + more)
    if view.evidence:
        lines += ["", "Evidence:", ""]
        lines += [f"- {_inline(e)}" for e in view.evidence]
    if view.hint and entry.result.status is Status.FAIL:
        lines += ["", f"Suggestion: {_inline(view.hint)}"]
    lines += ["", f"_Checked by: {view.how_checked}_", ""]
    return lines


def render_markdown(report: AuditReport) -> str:
    """Render the full report as Markdown."""
    s = report.summary
    out = [
        "# SpecGuard audit",
        "",
        f"- **File:** `{report.document.path or 'in-memory text'}`",
        f"- **Specification:** {report.specification_name}",
        f"- **Requirements:** {s.total_requirements}",
        f"- **Compliance among verified requirements:** {_pct(s.compliance_score)}",
        f"- **Verification coverage:** {_pct(s.verification_coverage)}",
        "",
        "| Status | Count |",
        "| --- | ---: |",
    ]
    out += [f"| {st.value} | {s.counts.get(st.value, 0)} |" for st in Status]
    out.append("")
    if s.verified < s.total_requirements:
        out += [
            f"{s.total_requirements - s.verified} of {s.total_requirements} requirement(s) were "
            "not tested. They are not counted as passes.",
            "",
        ]
    out += [f"> Note: {n}" for n in report.notices]
    if report.notices:
        out.append("")

    order = [Status.FAIL, Status.ERROR, Status.WARNING, Status.UNVERIFIED]
    for status in order:
        entries = sorted(
            report.by_status(status), key=lambda e: SEVERITY_ORDER[e.requirement.severity]
        )
        if not entries:
            continue
        out += [f"## {_ICON[status].title()} ({len(entries)})", ""]
        for entry in entries:
            out += _entry_block(entry)

    passed = report.by_status(Status.PASS)
    if passed:
        out += [f"## Passed ({len(passed)})", ""]
        out += [f"- `{e.requirement.id}` {_inline(e.requirement.description)}" for e in passed]
        out.append("")
    out.append(
        f"_Generated by SpecGuard {report.specguard_version}. SpecGuard checks instruction "
        "compliance; it does not detect AI authorship._"
    )
    return "\n".join(out) + "\n"
